apiVersion: apps/v1
kind: Deployment
metadata:
  name: nature
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nature
  template:
    metadata:
      labels:
        app: nature
    spec:
      containers:
      - name: nature
        image: sivaram9087/nature:latest # update with your Docker Hub image
        ports:
        - containerPort: 80
